'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TariffSoapBinding", [Namespace]:="http://189.254.103.147:8088/sia/services/Tariff")>  _
    Partial Public Class TariffService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getTariffOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getTariffIntOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ProtGTPortal.My.MySettings.Default.ProtGTPortal_WebReference_TariffService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getTariffCompleted As getTariffCompletedEventHandler
        
        '''<remarks/>
        Public Event getTariffIntCompleted As getTariffIntCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://189.254.103.147:8088/sia/services/Tariff")>  _
        Public Function getTariff(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Long) As <System.Xml.Serialization.SoapElementAttribute("getTariffReturn")> String
            Dim results() As Object = Me.Invoke("getTariff", New Object() {userId, passwd, srsRatingId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getTariffAsync(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Long)
            Me.getTariffAsync(userId, passwd, srsRatingId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getTariffAsync(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Long, ByVal userState As Object)
            If (Me.getTariffOperationCompleted Is Nothing) Then
                Me.getTariffOperationCompleted = AddressOf Me.OngetTariffOperationCompleted
            End If
            Me.InvokeAsync("getTariff", New Object() {userId, passwd, srsRatingId}, Me.getTariffOperationCompleted, userState)
        End Sub
        
        Private Sub OngetTariffOperationCompleted(ByVal arg As Object)
            If (Not (Me.getTariffCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getTariffCompleted(Me, New getTariffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://189.254.103.147:8088/sia/services/Tariff")>  _
        Public Function getTariffInt(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Integer) As <System.Xml.Serialization.SoapElementAttribute("getTariffIntReturn")> String
            Dim results() As Object = Me.Invoke("getTariffInt", New Object() {userId, passwd, srsRatingId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getTariffIntAsync(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Integer)
            Me.getTariffIntAsync(userId, passwd, srsRatingId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getTariffIntAsync(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Integer, ByVal userState As Object)
            If (Me.getTariffIntOperationCompleted Is Nothing) Then
                Me.getTariffIntOperationCompleted = AddressOf Me.OngetTariffIntOperationCompleted
            End If
            Me.InvokeAsync("getTariffInt", New Object() {userId, passwd, srsRatingId}, Me.getTariffIntOperationCompleted, userState)
        End Sub
        
        Private Sub OngetTariffIntOperationCompleted(ByVal arg As Object)
            If (Not (Me.getTariffIntCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getTariffIntCompleted(Me, New getTariffIntCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub getTariffCompletedEventHandler(ByVal sender As Object, ByVal e As getTariffCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getTariffCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub getTariffIntCompletedEventHandler(ByVal sender As Object, ByVal e As getTariffIntCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getTariffIntCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
