.DefaultFont, BODY, BODY.IE_M7, BODY.IE_M8, BODY.Win6, TEXTAREA, SELECT, INPUT, .c_hf INPUT, BUTTON, .c_h .signOut, .EditArea, .ExternalClass {font-family:Segoe UI, Tahoma,Verdana,Arial,sans-serif;line-height:normal;}BODY{font-size:0,83%}.App .Middle, .App .FooterContainer, #PageBottomElt,.ManageFolders #mainLayoutTable, .ManageFolders #uxp_ftr_control {font-size:90%}A{text-decoration:none;}.EditArea, .ExternalClass{font-size:10pt;}B, STRONG, .BoldText{font-weight: bold;}I, EM, .TextItalic{font-style: italic;}.TextSizeLargeLoc{font-size: 125%;}.ExcoClosed,.ExcoClosed:hover,.ExcoOpen,.ExcoOpen:hover,.g_sort_asc,.g_sort_desc,.g_close,.g_pdv_c,.g_pdv_o,.i_pn_f,.i_pn_f_d,.i_pn_l,.i_pn_l_d,.i_pn_n,.i_pn_n_d,.i_pn_p,.i_pn_p_d,.i_voicemail_s,.CogMenuOn, .lnav_topItem:hover .MenuCog, .TurnOnMenu .MenuCog,.lnav_topItem:hover .MenuCog:hover, .Hover .MenuCog,.i_att_s,.i_imp_hi_s,.i_imp_lo_s,.yl_sdi,.rd_sdi,.pr_sdi,.bl_sdi,.gr_sdi,.pi_sdi,.mr_m_c,.mr_m_r,.mr_r_a,.mr_r_d,.mr_r_t,.i_calllog,.i_ts,.i_voicemail,.i_help,.i_help_he,.i_new,.i_print,.i_refresh,.i_sortby,.i_info,.i_c_a_r,.i_c_a_rf,.i_c_a_rr,.i_c_a_u,.i_c_a_uf,.i_c_a_ur,.i_c_r,.i_c_rf,.i_c_rr,.i_c_ru,.i_c_ruf,.i_c_rur,.i_c_u,.i_c_uf,.i_c_ur{background-image:url(//gfx2.hotmail.com/mail/w4/pr04/ltr/i_strip.png);background-color:transparent;background-repeat:no-repeat;background-attachment:scroll;overflow:hidden}.ss_bl,.ss_br,.ss_tr,.HideH .FBA,.HideH .DetailToggleHover .FBA,.ShowH .FBA,.ShowH .DetailToggleHover .FBA,.HMLV .Collapsed IMG,.HMLV .Collapsed IMG:hover,.HMLV .Expanded IMG,.HMLV .Expanded IMG:hover,.i_cancel,.i_rm_n,.i_rm_n_d,.i_rm_p,.i_rm_p_d,.i_tagging,.mr_tb_a,.mr_tb_c,.mr_tb_d,.mr_tb_t{background-image:url(//gfx1.hotmail.com/mail/w4/pr04/ltr/r_strip.png);background-color:transparent;background-repeat:no-repeat;background-attachment:scroll;overflow:hidden}.fg IMG {background-image:url(//gfx2.hotmail.com/mail/w4/pr04/ltr/fg1.png)}.uf IMG {background-image:url(//gfx1.hotmail.com/mail/w4/pr04/ltr/fg0.png)}.i_refreshing{background-image:url(//gfx2.hotmail.com/mail/w4/pr04/ltr/prc.gif)}.i_clear{background-image:url(//gfx2.hotmail.com/mail/w4/pr04/ltr/clear.gif)}.i_refresh, .i_refreshing{border:none;overflow:hidden;background-repeat:no-repeat;height:16px;width:16px}.TableHeaderGradient{background-image: url(//gfx1.hotmail.com/mail/w4/pr04/ltr/table_header_gradient_1.png)}
.Draft .MsgPartGradient{background-image: url(//gfx1.hotmail.com/mail/w4/pr04/ltr/draft_header_gradient.gif)}
.FB{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/fadeBarCenter1.gif)}
.FBL{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/fadeBarLeft1.gif)}
.FBR{background-image: url(//gfx1.hotmail.com/mail/w4/pr04/ltr/fadeBarRight1.gif)}
.DetailToggleHover{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/fadeBarCenterHover1.gif)}
.DetailToggleHover .FBL{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/fadeBarLeftHover1.gif)}
.DetailToggleHover .FBR{background-image: url(//gfx1.hotmail.com/mail/w4/pr04/ltr/fadeBarRightHover1.gif)}
.ss_r{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/softShadowR.png)}
.ss_b{background-image: url(//gfx2.hotmail.com/mail/w4/pr04/ltr/softShadowB.png)}.HMLV .Content{background-image: url(//gfx1.hotmail.com/mail/w4/pr04/ltr/liveviews/gradient.png)}